kodebin.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin.c -o kodebin.lo 
kernel/main.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/exception.c -o kernel/exception.lo 
kernel/hash.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/hash.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/hash.c -o kernel/hash.lo 
kernel/debug.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/array.c -o kernel/array.lo 
kernel/extended/array.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/extended/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/extended/array.c -o kernel/extended/array.lo 
kernel/string.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/extended/fcall.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/extended/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/extended/fcall.c -o kernel/extended/fcall.lo 
kernel/require.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /home/ubuntu/workspace/kodebin-lib/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kernel/exit.c -o kernel/exit.lo 
kodebin/lib/curl.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/curl.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/curl.zep.c -o kodebin/lib/curl.lo 
kodebin/lib/dir.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/dir.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/dir.zep.c -o kodebin/lib/dir.lo 
kodebin/lib/files.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/files.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/files.zep.c -o kodebin/lib/files.lo 
kodebin/lib/folder.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/folder.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/folder.zep.c -o kodebin/lib/folder.lo 
kodebin/lib/github.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/github.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/lib/github.zep.c -o kodebin/lib/github.lo 
kodebin/security/password.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/security/password.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/security/password.zep.c -o kodebin/security/password.lo 
kodebin/security/patch.lo: /home/ubuntu/workspace/kodebin-lib/ext/kodebin/security/patch.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/ubuntu/workspace/kodebin-lib/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/ubuntu/workspace/kodebin-lib/ext/kodebin/security/patch.zep.c -o kodebin/security/patch.lo 
$(phplibdir)/kodebin.la: ./kodebin.la
	$(LIBTOOL) --mode=install cp ./kodebin.la $(phplibdir)

./kodebin.la: $(shared_objects_kodebin) $(KODEBIN_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_kodebin) $(KODEBIN_SHARED_LIBADD)

